#!/usr/bin/env perl

use warnings;
use strict;
use Daemon::Control;

use ENV::Util -load_dotenv;

use Cwd qw(abs_path);
use File::Basename;

my $abs_path = abs_path($0);
my $abs_dir  = dirname($0);

my @vars = qw[USER PASS HOST NAME];

if (grep { ! defined $ENV{"PD_AUTH_DB_$_"} } @vars) {
  die "Please define the DB connection variables: PD_AUTH_DB*\n";
}

Daemon::Control->new({
  name      =>  ucfirst lc $ENV{PD_AUTH_APP_NAME},
  lsb_start => '$syslog $remote_fs',
  lsb_stop  => '$syslog',
  lsb_sdesc => 'PerlDiver Authorisation Service',
  lsb_desc  => 'PerlDiver Authorisation Service',
  path      => $abs_path,

  program      => '/usr/bin/starman',
  program_args => [ '--workers', ($ENV{PD_AUTH_WORKER_COUNT} // 10), '-l', ":$ENV{PD_AUTH_APP_PORT}",
                    "$abs_dir/PerlDiverAuth/bin/app.psgi" ],

  user  => $ENV{PD_AUTH_OWNER},
  group => $ENV{PD_AUTH_GROUP},

  pid_file    => "/var/run/$ENV{PD_AUTH_APP_NAME}.pid",
  stderr_file => "$ENV{PD_AUTH_LOG_DIR}/error.log",
  stdout_file => "$ENV{PD_AUTH_LOG_DIR}/output.log",

  fork => 2,
})->run;
